tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y wget xvfb openjdk-11-jdk maven
      mvn dependency:resolve
  - command: |
      echo "Gitpod is ready. You can now create and run your Selenium scripts."
