tasks:
  - name: "Java Setup"
    init: |
      sudo apt update && sudo apt install -y openjdk-17-jdk maven
      mvn clean install
    command: |
      echo "Java setup complete."

ports:
  - port: 4444
    onOpen: notify

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-maven
